### ISSUE TITLE
Needs update for recent 1.6 patch

### ISSUE THREAD

**Issue by Amoeba00** [jackhumbert/mod_settings#3]
Please update for use with recent 1.6 patch.

**Comment by ordinateur14** [comment]
Yes please, It's actually one of the first mod I ever download because I wish to try let there be flight and it's broken :( 
Can we have an update about the situation..?

**Comment by Aiesha-z** [comment]
Let there be flight is the only mod i use.
Since 1.6 its not working. Everything load fine in log but still get script not loaded error when i press play and i dont have the mod menu and when in the car i cant move at all. Keyboard not responding.
I wish i can send you an error log but everything loaded in the log.

**Comment by jackhumbert** [comment]
Fixed in https://github.com/jackhumbert/mod_settings/commit/b2ba9717bafedfa3c084d7a04c5b986b5efd2e75 / v0.0.3
